# Generated by Django 4.1.7 on 2023-03-22 19:23

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogauthorsorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.blogauthor'),
        ),
    ]
