# Generated by Django 4.1.7 on 2023-03-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogdetailpage_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogauthorsorderable',
            old_name='author',
            new_name='authora',
        ),
    ]
