# Generated by Django 4.1.7 on 2023-03-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogdetailpage_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='blog_image',
            new_name='banner_image',
        ),
    ]
