# Generated by Django 4.1.7 on 2023-03-15 16:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('cta', wagtail.blocks.StructBlock([('cta_title', wagtail.blocks.CharBlock(max_length=40, required=True)), ('cta_text', wagtail.blocks.RichTextBlock(required=True)), ('cta_button_page', wagtail.blocks.PageChooserBlock(required=False)), ('cta_button_url', wagtail.blocks.URLBlock(required=False)), ('cta_button_text', wagtail.blocks.CharBlock(default='Aprende mas', max_length=30, required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
