# Generated by Django 4.1.7 on 2023-03-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Direccion de correo', max_length=100)),
                ('full_name', models.CharField(help_text='Nombre completo', max_length=100)),
            ],
        ),
    ]
